name: CI/CD Pipeline

# Trigger the workflow on push to staging or pull requests
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    name: xero
    runs-on: ubuntu-latest
    

    steps:
    - name: checkout repostory
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
       node-version: '14'

    - name: install depedencies
      run: npm install

    - name: run tests
      uses: npm test  
